services:
    post_context.controller.create_post:
        class: PostContext\PresentationBundle\Controller\PostController
        arguments:
            - @post_context.handlers.post_handler
            - @jms_serializer
