services:
    post_context.domain.channel_fetcher:
        class: PostContext\Domain\Service\ChannelFetcher
        arguments:
            - @post_context.infrastructure.channel_gateway

    post_context.domain.post_creator:
        class: PostContext\Domain\Service\MessageCreator
        arguments:
            - @post_context.infrastructure.channel_authorization_gateway
            - @post_context.infrastructure.post_repository

    post_context.domain.publisher_fetcher:
        class: PostContext\Domain\Service\PublisherFetcher
        arguments:
            - @post_context.infrastructure.publisher_repository
