services:
    post_context.infrastructure.channel_gateway:
        class: PostContext\InfrastructureBundle\Service\Channel\ChannelGateway
        arguments:
            - @post_context.infrastructure.channel_adapter
            - @post_context.infrastracture.circuit_breaker

    post_context.infrastructure.channel_authorization_gateway:
        class: PostContext\InfrastructureBundle\Service\ChannelAuthorization\ChannelAuthorizationGateway
        arguments:
            - @post_context.infrastructure.channel_authorization_adapter

    post_context.infrastructure.channel_adapter:
        class: PostContext\InfrastructureBundle\Service\Channel\ChannelAdapter
        arguments:
            - @post_context.infrastructure.request_handler
            - "http://127.0.0.1:8080"

    post_context.infrastructure.channel_authorization_adapter:
        class: PostContext\InfrastructureBundle\Service\ChannelAuthorization\ChannelAuthorizationAdapter
        arguments:
            - @post_context.infrastructure.request_handler
            - "http://127.0.0.1:8080"
