services:
    post_context.infrastructure.request_handler:
        class: PostContext\InfrastructureBundle\RequestHandler\Middleware\EventRequestHandler
        arguments:
            - @event_dispatcher
            - @post_context.infrastractrue.guzzle_request_handler

    post_context.infrastractrue.guzzle_request_handler:
        class: PostContext\InfrastructureBundle\RequestHandler\Middleware\GuzzleRequestHandler
        arguments:
            - @post_context.infrastructure.guzzle_http_client

    post_context.infrastractrue.json_response_listener:
        class: PostContext\InfrastructureBundle\RequestHandler\Listener\JsonResponseListener
        tags:
            - { name: kernel.event_listener, event: request_handler.received_response, method: onReceivedResponse }


    post_context.infrastructure.guzzle_http_client:
        class: GuzzleHttp\Client
